version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: https://github.com/Shenbagaraj11/mycicdrepo/script.sh
      timeout: 60
      runas: root
