version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt install npm
  build:
    commands:
      - echo Building app...
      - npm run build
artifacts:
  files:
    - '**/*'
